#!/usr/bin/env bash
# Generate language-specific stubs from proto/prompt_app.proto.
#   * Python stubs land in prompt_app/generated/.
#   * C++ stubs are generated by CMake at build time.
#
# Usage:
#   scripts/gen_proto.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_DIR="$ROOT/proto"
PY_OUT="$ROOT/prompt_app/generated"

mkdir -p "$PY_OUT"
touch "$PY_OUT/__init__.py"

python -m grpc_tools.protoc \
  --proto_path="$PROTO_DIR" \
  --python_out="$PY_OUT" \
  --grpc_python_out="$PY_OUT" \
  "$PROTO_DIR/prompt_app.proto"

# grpcio-tools <1.62 emits absolute imports we need to rewrite to keep
# generated/ self-contained.
sed -i 's/^import prompt_app_pb2/from . import prompt_app_pb2/' \
  "$PY_OUT/prompt_app_pb2_grpc.py" 2>/dev/null || true

echo "wrote stubs to $PY_OUT"
